### ISSUE TITLE
[suggestion] Nether and End stone variations?

### ISSUE THREAD

**Issue by xkforce** [GlobbyPotato/Rockhounding_Rocks#7]
This mod does an excellent job filling out the overworld with new stone types but the nether and end are pretty much stone deserts are far as variety goes.  I suppose that people could use COFH world to distribute these stone types over different dimensions but it'd be nice to see some stone types that feel like they belong in the other dimensions too.

**Comment by GlobbyPotato** [comment]
That would be possible I guess, I could move some color themed rocks there and find something else  catchy for those dimensions.

**Comment by xkforce** [comment]
Neat.  Nether and End sure could use it.

**Comment by NotAVerb** [comment]
Do you mean move some of the stones that already generate in the overworld to the other dimensions?
In that case what about whitelists in the config for allowed stones in the end and nether? Expanding upon the simple toggle that just generates all stones.

**Comment by xkforce** [comment]
I've toyed with the idea of moving a few of them with COFH world since there are a few I could see fitting the theme of the nether or the end (brown aventurine and the nether or snowflake obsidian and the end?) but I think a lot of the problem is that it's harder to design stone types specifically for other dimensions.  The overworld is pretty easy to flesh out because it's basically Earth as we know it but the other two are what they are precisely because they aren't familiar environments.  The nether is hell and the end is... the end.  Overworld stone types tend to feel familiar to us because the environment is very Earth-like.  Nether stone tends to feel like something you'd find in the mythological accounts of an underworld/hell and the end reminds me of somewhere outside the Earth like the moon or somewhere else equally sterile.

I've been trying to make my own with contenttweaker such as sulfur and other blocks that are mythologically associated with hell/the underworld but it's a problematic solution given that they're all tile entities...  As far as the end goes, I've been looking to moon rocks and the like as inspiration.

Thoughts?

**Comment by GlobbyPotato** [comment]
I'd consider also red carnerlian in the nether because it appears "bloody-like" and stichtite in the end because though the appearence, the polished block is similar to purpur. The problem with the other dimensions is the underground material. Overworld has a plain stone so everything fits. Fitting stuff on the patterned netherrack or end stone makes it a too explicit transition because unless I can compromise by using as mask the vanilla -ite rocks, I use their real-life theme.

If there is already a well settled mod that allows to move the single rocks on a specific dimension I'd suggest to use it, so you can have a personal customization. By my side I added back then a whitelist for dimensions where all the rocks will generate, not specifying the single rocks because it would be pointless to say which of the 112 rocks generates where. I use the overworkd as reference because biomes allow a selective generation.
